spring:
  datasource:
    url: jdbc:mysql://localhost:3306/{ database }
    username: { username }
    password: { password }
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret:
    key: { jwt Key }